### ISSUE TITLE
(line for line in lines if pattern in line) ?

### ISSUE THREAD

**Issue by gavingc** [anandology/python-practice-book#8]
Possible type in section 5.3.1. Example: Reading multiple files:

def grep(pattern, lines):
    return (line for line in lines if pattern in lines)

should that be:

def grep(pattern, lines):
    return (line for line in lines if pattern in line)

**Comment by anandology** [comment]
Fixed in aca7d798997f760232e252f430fd78b6a3a76e16.

Thanks @gavingc
